apiVersion: v1
kind: Pod
metadata:
  name: announcement
  labels:
    app: announcement
spec:
  containers:
    - name: announcement
      image: rakesh1019/javahome:tagVersion
      ports:
        - containerPort: 8080
